import fs from 'fs';

function markdownToHTML(md: string): string {
  return md
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/gs, (match) => `<ul>${match}</ul>`)
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[hul]|<\/[hul]|<p|<\/p)(.+)$/gm, '<p>$1</p>')
    .replace(/<p><\/p>/g, '');
}

export function generateReport(analysisText: string, outputPath: string = './report.html') {
  const body = markdownToHTML(analysisText);
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DevLens — Code Analysis Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0d1117;
      color: #e6edf3;
      line-height: 1.7;
      padding: 2rem;
    }

    .container {
      max-width: 860px;
      margin: 0 auto;
    }

    header {
      border-bottom: 1px solid #30363d;
      padding-bottom: 1.5rem;
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 2rem;
      font-weight: 700;
      color: #58a6ff;
      letter-spacing: -0.5px;
    }

    header p {
      color: #8b949e;
      margin-top: 0.25rem;
      font-size: 0.9rem;
    }

    h2 {
      font-size: 1.25rem;
      font-weight: 600;
      color: #f0f6fc;
      margin: 2rem 0 0.75rem;
      padding-bottom: 0.4rem;
      border-bottom: 1px solid #21262d;
    }

    h3 {
      font-size: 1.05rem;
      font-weight: 600;
      color: #cdd9e5;
      margin: 1.25rem 0 0.5rem;
    }

    h4 {
      font-size: 0.95rem;
      font-weight: 600;
      color: #8b949e;
      margin: 1rem 0 0.25rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    p {
      margin-bottom: 0.75rem;
      color: #cdd9e5;
    }

    ul {
      padding-left: 1.5rem;
      margin-bottom: 0.75rem;
    }

    li {
      color: #cdd9e5;
      margin-bottom: 0.3rem;
    }

    strong {
      color: #f0f6fc;
      font-weight: 600;
    }

    code {
      background: #161b22;
      color: #79c0ff;
      padding: 0.15em 0.4em;
      border-radius: 4px;
      font-size: 0.875em;
      font-family: 'SFMono-Regular', Consolas, monospace;
    }

    .content {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 8px;
      padding: 2rem;
    }

    footer {
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid #21262d;
      color: #8b949e;
      font-size: 0.8rem;
      text-align: center;
    }

    footer a { color: #58a6ff; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>DevLens</h1>
      <p>Code Analysis Report &mdash; Generated ${date}</p>
    </header>
    <div class="content">
      ${body}
    </div>
    <footer>
      Generated by <a href="https://github.com/soham842op/Devlens">DevLens</a> &mdash; privacy-first local code analysis
    </footer>
  </div>
</body>
</html>`;

  fs.writeFileSync(outputPath, html, 'utf8');
  return outputPath;
}
